# Generated by Django 4.2.5 on 2023-09-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_alter_curso_nivel_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('A', 'Avançado'), ('B', 'Básico'), ('I', 'Intermediário')], default='B', max_length=1),
        ),
    ]
